[package]
name = "terminal"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
model.workspace = true
metadata.workspace = true

chrono.workspace = true
secrecy.workspace = true
subtle.workspace = true
tracing.workspace = true
tokio.workspace = true
tokio-util.workspace = true
portable-pty.workspace = true
vt100.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true
nix.features = ["signal", "process"]

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
