// Ait names declared by Rust capability components.
// Verify with scripts/check-paseo-client-methods.py.
import { RELAY_METHODS } from "./relay-methods";
export interface MethodSpec {
  method: string;
  kind: "request" | "event" | "response";
  channel: number;
  response: string | null;
}

export const METHODS: Readonly<Record<string, MethodSpec>> = {
  ...RELAY_METHODS,
  "daemon.get_status.request": {
    method: "daemon.get_status.request",
    kind: "request",
    channel: 1,
    response: "daemon.get_status.response",
  },
  "daemon.get_pairing_offer.request": {
    method: "daemon.get_pairing_offer.request",
    kind: "request",
    channel: 1,
    response: "daemon.get_pairing_offer.response",
  },
  "daemon.config.reload.request": {
    method: "daemon.config.reload.request",
    kind: "request",
    channel: 1,
    response: "daemon.config.reload.response",
  },
  "daemon.update.request": {
    method: "daemon.update.request",
    kind: "request",
    channel: 1,
    response: "daemon.update.response",
  },
  "diagnostics.request": {
    method: "diagnostics.request",
    kind: "request",
    channel: 1,
    response: "diagnostics.response",
  },
  "daemon.config.get.request": {
    method: "daemon.config.get.request",
    kind: "request",
    channel: 1,
    response: "daemon.config.get.response",
  },
  "daemon.config.set.request": {
    method: "daemon.config.set.request",
    kind: "request",
    channel: 1,
    response: "daemon.config.set.response",
  },
  "server.restart.request": {
    method: "server.restart.request",
    kind: "request",
    channel: 1,
    response: "status:restart_requested",
  },
  "server.shutdown.request": {
    method: "server.shutdown.request",
    kind: "request",
    channel: 1,
    response: "status:shutdown_requested",
  },
  "project.list.request": {
    method: "project.list.request",
    kind: "request",
    channel: 1,
    response: "project.list.response",
  },
  "project.add.request": {
    method: "project.add.request",
    kind: "request",
    channel: 1,
    response: "project.add.response",
  },
  "project.create_directory.request": {
    method: "project.create_directory.request",
    kind: "request",
    channel: 1,
    response: "project.create_directory.response",
  },
  "project.github.clone.request": {
    method: "project.github.clone.request",
    kind: "request",
    channel: 1,
    response: "project.github.clone.response",
  },
  "project.rename.request": {
    method: "project.rename.request",
    kind: "request",
    channel: 1,
    response: "project.rename.response",
  },
  "project.remove.request": {
    method: "project.remove.request",
    kind: "request",
    channel: 1,
    response: "project.remove.response",
  },
  "project.icon.set.request": {
    method: "project.icon.set.request",
    kind: "request",
    channel: 1,
    response: "project.icon.set.response",
  },
  "project.icon.get.request": {
    method: "project.icon.get.request",
    kind: "request",
    channel: 1,
    response: "project.icon.get.response",
  },
  "project.config.read.request": {
    method: "project.config.read.request",
    kind: "request",
    channel: 1,
    response: "project.config.read.response",
  },
  "project.config.write.request": {
    method: "project.config.write.request",
    kind: "request",
    channel: 1,
    response: "project.config.write.response",
  },
  "workspace.list.request": {
    method: "workspace.list.request",
    kind: "request",
    channel: 1,
    response: "workspace.list.response",
  },
  "workspace.open.request": {
    method: "workspace.open.request",
    kind: "request",
    channel: 1,
    response: "workspace.open.response",
  },
  "workspace.create.request": {
    method: "workspace.create.request",
    kind: "request",
    channel: 1,
    response: "workspace.create.response",
  },
  "workspace.archive.request": {
    method: "workspace.archive.request",
    kind: "request",
    channel: 1,
    response: "workspace.archive.response",
  },
  "workspace.title.set.request": {
    method: "workspace.title.set.request",
    kind: "request",
    channel: 1,
    response: "workspace.title.set.response",
  },
  "workspace.pin.set.request": {
    method: "workspace.pin.set.request",
    kind: "request",
    channel: 1,
    response: "workspace.pin.set.response",
  },
  "workspace.clear_attention.request": {
    method: "workspace.clear_attention.request",
    kind: "request",
    channel: 1,
    response: "workspace.clear_attention.response",
  },
  "workspace.mark_unread.request": {
    method: "workspace.mark_unread.request",
    kind: "request",
    channel: 1,
    response: "workspace.mark_unread.response",
  },
  "workspace.recovery.inspect.request": {
    method: "workspace.recovery.inspect.request",
    kind: "request",
    channel: 1,
    response: "workspace.recovery.inspect.response",
  },
  "workspace.recovery.restore.request": {
    method: "workspace.recovery.restore.request",
    kind: "request",
    channel: 1,
    response: "workspace.recovery.restore.response",
  },
  "workspace.github.search_repositories.request": {
    method: "workspace.github.search_repositories.request",
    kind: "request",
    channel: 1,
    response: "workspace.github.search_repositories.response",
  },
  "workspace.label.list.request": {
    method: "workspace.label.list.request",
    kind: "request",
    channel: 1,
    response: "workspace.label.list.response",
  },
  "workspace.label.assignment.set.request": {
    method: "workspace.label.assignment.set.request",
    kind: "request",
    channel: 1,
    response: "workspace.label.assignment.set.response",
  },
  "workspace.label.update.request": {
    method: "workspace.label.update.request",
    kind: "request",
    channel: 1,
    response: "workspace.label.update.response",
  },
  "workspace.label.delete.inspect.request": {
    method: "workspace.label.delete.inspect.request",
    kind: "request",
    channel: 1,
    response: "workspace.label.delete.inspect.response",
  },
  "workspace.label.delete.request": {
    method: "workspace.label.delete.request",
    kind: "request",
    channel: 1,
    response: "workspace.label.delete.response",
  },
  "workspace.worktree.list.request": {
    method: "workspace.worktree.list.request",
    kind: "request",
    channel: 1,
    response: "workspace.worktree.list.response",
  },
  "workspace.worktree.create.request": {
    method: "workspace.worktree.create.request",
    kind: "request",
    channel: 1,
    response: "workspace.worktree.create.response",
  },
  "workspace.worktree.archive.request": {
    method: "workspace.worktree.archive.request",
    kind: "request",
    channel: 1,
    response: "workspace.worktree.archive.response",
  },
  "workspace.setup.status.request": {
    method: "workspace.setup.status.request",
    kind: "request",
    channel: 1,
    response: "workspace.setup.status.response",
  },
  "workspace.setup.run.request": {
    method: "workspace.setup.run.request",
    kind: "request",
    channel: 1,
    response: "workspace.setup.run.response",
  },
  "workspace.script.list.request": {
    method: "workspace.script.list.request",
    kind: "request",
    channel: 1,
    response: "workspace.script.list.response",
  },
  "workspace.script.start.request": {
    method: "workspace.script.start.request",
    kind: "request",
    channel: 1,
    response: "workspace.script.start.response",
  },
  "workspace.script.stop.request": {
    method: "workspace.script.stop.request",
    kind: "request",
    channel: 1,
    response: "workspace.script.stop.response",
  },
  "agent.list.request": {
    method: "agent.list.request",
    kind: "request",
    channel: 0,
    response: "agent.list.response",
  },
  "agent.get.request": {
    method: "agent.get.request",
    kind: "request",
    channel: 0,
    response: "agent.get.response",
  },
  "agent.history.get.request": {
    method: "agent.history.get.request",
    kind: "request",
    channel: 0,
    response: "agent.history.get.response",
  },
  "agent.create.request": {
    method: "agent.create.request",
    kind: "request",
    channel: 0,
    response: "agent.create.response",
  },
  "agent.resume.request": {
    method: "agent.resume.request",
    kind: "request",
    channel: 0,
    response: "status:agent_resumed",
  },
  "agent.import.request": {
    method: "agent.import.request",
    kind: "request",
    channel: 0,
    response: "status:agent_resumed",
  },
  "agent.refresh.request": {
    method: "agent.refresh.request",
    kind: "request",
    channel: 0,
    response: "status:agent_refreshed",
  },
  "agent.update.request": {
    method: "agent.update.request",
    kind: "request",
    channel: 0,
    response: "agent.update.response",
  },
  "agent.message.send.request": {
    method: "agent.message.send.request",
    kind: "request",
    channel: 0,
    response: "agent.message.send.response",
  },
  "agent.finish.wait.request": {
    method: "agent.finish.wait.request",
    kind: "request",
    channel: 0,
    response: "agent.finish.wait.response",
  },
  "agent.cancel.request": {
    method: "agent.cancel.request",
    kind: "request",
    channel: 0,
    response: "agent.cancel.response",
  },
  "agent.archive.request": {
    method: "agent.archive.request",
    kind: "request",
    channel: 0,
    response: "agent.archive.response",
  },
  "agent.delete.request": {
    method: "agent.delete.request",
    kind: "request",
    channel: 0,
    response: "agent.delete.response",
  },
  "agent.detach.request": {
    method: "agent.detach.request",
    kind: "request",
    channel: 0,
    response: "agent.detach.response",
  },
  "agent.rewind.request": {
    method: "agent.rewind.request",
    kind: "request",
    channel: 0,
    response: "agent.rewind.response",
  },
  "agent.attention.clear.request": {
    method: "agent.attention.clear.request",
    kind: "request",
    channel: 0,
    response: null,
  },
  "agent.items.close.request": {
    method: "agent.items.close.request",
    kind: "request",
    channel: 0,
    response: "agent.items.close.response",
  },
  "agent.commands.list.request": {
    method: "agent.commands.list.request",
    kind: "request",
    channel: 0,
    response: "agent.commands.list.response",
  },
  "agent.mode.set.request": {
    method: "agent.mode.set.request",
    kind: "request",
    channel: 0,
    response: "agent.mode.set.response",
  },
  "agent.model.set.request": {
    method: "agent.model.set.request",
    kind: "request",
    channel: 0,
    response: "agent.model.set.response",
  },
  "agent.thinking.set.request": {
    method: "agent.thinking.set.request",
    kind: "request",
    channel: 0,
    response: "agent.thinking.set.response",
  },
  "agent.feature.set.request": {
    method: "agent.feature.set.request",
    kind: "request",
    channel: 0,
    response: "agent.feature.set.response",
  },
  "agent.config.apply.request": {
    method: "agent.config.apply.request",
    kind: "request",
    channel: 0,
    response: "agent.config.apply.response",
  },
  "agent.permission.resolve.request": {
    method: "agent.permission.resolve.request",
    kind: "request",
    channel: 0,
    response: null,
  },
  "agent.timeline.get.request": {
    method: "agent.timeline.get.request",
    kind: "request",
    channel: 0,
    response: "agent.timeline.get.response",
  },
  "agent.timeline.search.request": {
    method: "agent.timeline.search.request",
    kind: "request",
    channel: 0,
    response: "agent.timeline.search.response",
  },
  "agent.timeline.list_prompts.request": {
    method: "agent.timeline.list_prompts.request",
    kind: "request",
    channel: 0,
    response: "agent.timeline.list_prompts.response",
  },
  "agent.timeline.append.request": {
    method: "agent.timeline.append.request",
    kind: "request",
    channel: 0,
    response: "agent.timeline.append.response",
  },
  "agent.timeline.set_subscription.request": {
    method: "agent.timeline.set_subscription.request",
    kind: "request",
    channel: 0,
    response: "agent.timeline.set_subscription.response",
  },
  "agent.fork_context.request": {
    method: "agent.fork_context.request",
    kind: "request",
    channel: 0,
    response: "agent.fork_context.response",
  },
  "agent.provider_subagents.list.request": {
    method: "agent.provider_subagents.list.request",
    kind: "request",
    channel: 0,
    response: "agent.provider_subagents.list.response",
  },
  "agent.provider_subagents.timeline.get.request": {
    method: "agent.provider_subagents.timeline.get.request",
    kind: "request",
    channel: 0,
    response: "agent.provider_subagents.timeline.get.response",
  },
  "provider.available.list.request": {
    method: "provider.available.list.request",
    kind: "request",
    channel: 0,
    response: "provider.available.list.response",
  },
  "provider.models.list.request": {
    method: "provider.models.list.request",
    kind: "request",
    channel: 0,
    response: "provider.models.list.response",
  },
  "provider.modes.list.request": {
    method: "provider.modes.list.request",
    kind: "request",
    channel: 0,
    response: "provider.modes.list.response",
  },
  "provider.features.list.request": {
    method: "provider.features.list.request",
    kind: "request",
    channel: 0,
    response: "provider.features.list.response",
  },
  "provider.snapshot.get.request": {
    method: "provider.snapshot.get.request",
    kind: "request",
    channel: 0,
    response: "provider.snapshot.get.response",
  },
  "provider.snapshot.refresh.request": {
    method: "provider.snapshot.refresh.request",
    kind: "request",
    channel: 0,
    response: "provider.snapshot.refresh.response",
  },
  "provider.diagnostic.request": {
    method: "provider.diagnostic.request",
    kind: "request",
    channel: 0,
    response: "provider.diagnostic.response",
  },
  "provider.usage.list.request": {
    method: "provider.usage.list.request",
    kind: "request",
    channel: 0,
    response: "provider.usage.list.response",
  },
  "provider.sessions.recent.list.request": {
    method: "provider.sessions.recent.list.request",
    kind: "request",
    channel: 0,
    response: "provider.sessions.recent.list.response",
  },
  "agent.skills.get_status.request": {
    method: "agent.skills.get_status.request",
    kind: "request",
    channel: 0,
    response: "agent.skills.get_status.response",
  },
  "agent.skills.reconcile.request": {
    method: "agent.skills.reconcile.request",
    kind: "request",
    channel: 0,
    response: "agent.skills.reconcile.response",
  },
  "agent.skills.uninstall.request": {
    method: "agent.skills.uninstall.request",
    kind: "request",
    channel: 0,
    response: "agent.skills.uninstall.response",
  },
  "agent.skills.save_selection.request": {
    method: "agent.skills.save_selection.request",
    kind: "request",
    channel: 0,
    response: "agent.skills.save_selection.response",
  },
  "agent.skills.import_legacy_selection.request": {
    method: "agent.skills.import_legacy_selection.request",
    kind: "request",
    channel: 0,
    response: "agent.skills.import_legacy_selection.response",
  },
  "checkout.status.get.request": {
    method: "checkout.status.get.request",
    kind: "request",
    channel: 2,
    response: "checkout.status.get.response",
  },
  "checkout.refresh.request": {
    method: "checkout.refresh.request",
    kind: "request",
    channel: 2,
    response: "checkout.refresh.response",
  },
  "checkout.diff.get.request": {
    method: "checkout.diff.get.request",
    kind: "request",
    channel: 2,
    response: "checkout.diff.get.response",
  },
  "checkout.diff.subscribe.request": {
    method: "checkout.diff.subscribe.request",
    kind: "request",
    channel: 2,
    response: "checkout.diff.subscribe.response",
  },
  "checkout.diff.unsubscribe.request": {
    method: "checkout.diff.unsubscribe.request",
    kind: "request",
    channel: 2,
    response: null,
  },
  "checkout.commits.list.request": {
    method: "checkout.commits.list.request",
    kind: "request",
    channel: 2,
    response: "checkout.commits.list.response",
  },
  "checkout.commits.file_diff.request": {
    method: "checkout.commits.file_diff.request",
    kind: "request",
    channel: 2,
    response: "checkout.commits.file_diff.response",
  },
  "checkout.branch.validate.request": {
    method: "checkout.branch.validate.request",
    kind: "request",
    channel: 2,
    response: "checkout.branch.validate.response",
  },
  "checkout.branch.suggestions.request": {
    method: "checkout.branch.suggestions.request",
    kind: "request",
    channel: 2,
    response: "checkout.branch.suggestions.response",
  },
  "checkout.branch.switch.request": {
    method: "checkout.branch.switch.request",
    kind: "request",
    channel: 2,
    response: "checkout.branch.switch.response",
  },
  "checkout.rename_branch.request": {
    method: "checkout.rename_branch.request",
    kind: "request",
    channel: 2,
    response: "checkout.rename_branch.response",
  },
  "checkout.commit.request": {
    method: "checkout.commit.request",
    kind: "request",
    channel: 2,
    response: "checkout.commit.response",
  },
  "checkout.merge.request": {
    method: "checkout.merge.request",
    kind: "request",
    channel: 2,
    response: "checkout.merge.response",
  },
  "checkout.merge_from_base.request": {
    method: "checkout.merge_from_base.request",
    kind: "request",
    channel: 2,
    response: "checkout.merge_from_base.response",
  },
  "checkout.pull.request": {
    method: "checkout.pull.request",
    kind: "request",
    channel: 2,
    response: "checkout.pull.response",
  },
  "checkout.push.request": {
    method: "checkout.push.request",
    kind: "request",
    channel: 2,
    response: "checkout.push.response",
  },
  "checkout.discard_changes.request": {
    method: "checkout.discard_changes.request",
    kind: "request",
    channel: 2,
    response: "checkout.discard_changes.response",
  },
  "checkout.stash.save.request": {
    method: "checkout.stash.save.request",
    kind: "request",
    channel: 2,
    response: "checkout.stash.save.response",
  },
  "checkout.stash.pop.request": {
    method: "checkout.stash.pop.request",
    kind: "request",
    channel: 2,
    response: "checkout.stash.pop.response",
  },
  "checkout.stash.list.request": {
    method: "checkout.stash.list.request",
    kind: "request",
    channel: 2,
    response: "checkout.stash.list.response",
  },
  "forge.search.request": {
    method: "forge.search.request",
    kind: "request",
    channel: 2,
    response: "forge.search.response",
  },
  "github.search.request": {
    method: "github.search.request",
    kind: "request",
    channel: 2,
    response: "github.search.response",
  },
  "checkout.pr.create.request": {
    method: "checkout.pr.create.request",
    kind: "request",
    channel: 2,
    response: "checkout.pr.create.response",
  },
  "checkout.pr.merge.request": {
    method: "checkout.pr.merge.request",
    kind: "request",
    channel: 2,
    response: "checkout.pr.merge.response",
  },
  "checkout.pr.status.request": {
    method: "checkout.pr.status.request",
    kind: "request",
    channel: 2,
    response: "checkout.pr.status.response",
  },
  "checkout.pr.timeline.request": {
    method: "checkout.pr.timeline.request",
    kind: "request",
    channel: 2,
    response: "checkout.pr.timeline.response",
  },
  "checkout.forge.set_auto_merge.request": {
    method: "checkout.forge.set_auto_merge.request",
    kind: "request",
    channel: 2,
    response: "checkout.forge.set_auto_merge.response",
  },
  "checkout.forge.get_check_details.request": {
    method: "checkout.forge.get_check_details.request",
    kind: "request",
    channel: 2,
    response: "checkout.forge.get_check_details.response",
  },
  "checkout.github.set_auto_merge.request": {
    method: "checkout.github.set_auto_merge.request",
    kind: "request",
    channel: 2,
    response: "checkout.github.set_auto_merge.response",
  },
  "checkout.github.get_check_details.request": {
    method: "checkout.github.get_check_details.request",
    kind: "request",
    channel: 2,
    response: "checkout.github.get_check_details.response",
  },
  "directory.suggestions.request": {
    method: "directory.suggestions.request",
    kind: "request",
    channel: 2,
    response: "directory.suggestions.response",
  },
  "fs.explorer.request": {
    method: "fs.explorer.request",
    kind: "request",
    channel: 2,
    response: "fs.explorer.response",
  },
  "fs.file.subscribe.request": {
    method: "fs.file.subscribe.request",
    kind: "request",
    channel: 2,
    response: "fs.file.subscribe.response",
  },
  "fs.file.unsubscribe.request": {
    method: "fs.file.unsubscribe.request",
    kind: "request",
    channel: 2,
    response: "fs.file.unsubscribe.response",
  },
  "fs.file.write.request": {
    method: "fs.file.write.request",
    kind: "request",
    channel: 2,
    response: "fs.file.write.response",
  },
  "fs.entry.create.request": {
    method: "fs.entry.create.request",
    kind: "request",
    channel: 2,
    response: "fs.entry.create.response",
  },
  "fs.entry.rename.request": {
    method: "fs.entry.rename.request",
    kind: "request",
    channel: 2,
    response: "fs.entry.rename.response",
  },
  "fs.entry.duplicate.request": {
    method: "fs.entry.duplicate.request",
    kind: "request",
    channel: 2,
    response: "fs.entry.duplicate.response",
  },
  "fs.entry.delete.request": {
    method: "fs.entry.delete.request",
    kind: "request",
    channel: 2,
    response: "fs.entry.delete.response",
  },
  "fs.file.download_token.request": {
    method: "fs.file.download_token.request",
    kind: "request",
    channel: 2,
    response: "fs.file.download_token.response",
  },
  "file.upload.request": {
    method: "file.upload.request",
    kind: "request",
    channel: 2,
    response: "file.upload.response",
  },
  "terminal.list.request": {
    method: "terminal.list.request",
    kind: "request",
    channel: 1,
    response: "terminal.list.response",
  },
  "terminal.list.subscribe.request": {
    method: "terminal.list.subscribe.request",
    kind: "request",
    channel: 1,
    response: "terminal.list.changed",
  },
  "terminal.list.unsubscribe.request": {
    method: "terminal.list.unsubscribe.request",
    kind: "request",
    channel: 1,
    response: null,
  },
  "terminal.create.request": {
    method: "terminal.create.request",
    kind: "request",
    channel: 1,
    response: "terminal.create.response",
  },
  "terminal.rename.request": {
    method: "terminal.rename.request",
    kind: "request",
    channel: 1,
    response: "terminal.rename.response",
  },
  "terminal.subscribe.request": {
    method: "terminal.subscribe.request",
    kind: "request",
    channel: 1,
    response: "terminal.subscribe.response",
  },
  "terminal.unsubscribe.request": {
    method: "terminal.unsubscribe.request",
    kind: "request",
    channel: 1,
    response: null,
  },
  "terminal.input": {
    method: "terminal.input",
    kind: "event",
    channel: 1,
    response: null,
  },
  "terminal.kill.request": {
    method: "terminal.kill.request",
    kind: "request",
    channel: 1,
    response: "terminal.kill.response",
  },
  "terminal.capture.request": {
    method: "terminal.capture.request",
    kind: "request",
    channel: 1,
    response: "terminal.capture.response",
  },
  "schedule.create.request": {
    method: "schedule.create.request",
    kind: "request",
    channel: 3,
    response: "schedule.create.response",
  },
  "schedule.list.request": {
    method: "schedule.list.request",
    kind: "request",
    channel: 3,
    response: "schedule.list.response",
  },
  "schedule.inspect.request": {
    method: "schedule.inspect.request",
    kind: "request",
    channel: 3,
    response: "schedule.inspect.response",
  },
  "schedule.logs.request": {
    method: "schedule.logs.request",
    kind: "request",
    channel: 3,
    response: "schedule.logs.response",
  },
  "schedule.update.request": {
    method: "schedule.update.request",
    kind: "request",
    channel: 3,
    response: "schedule.update.response",
  },
  "schedule.pause.request": {
    method: "schedule.pause.request",
    kind: "request",
    channel: 3,
    response: "schedule.pause.response",
  },
  "schedule.resume.request": {
    method: "schedule.resume.request",
    kind: "request",
    channel: 3,
    response: "schedule.resume.response",
  },
  "schedule.delete.request": {
    method: "schedule.delete.request",
    kind: "request",
    channel: 3,
    response: "schedule.delete.response",
  },
  "schedule.run_once.request": {
    method: "schedule.run_once.request",
    kind: "request",
    channel: 3,
    response: "schedule.run_once.response",
  },
  "voice.mode.set.request": {
    method: "voice.mode.set.request",
    kind: "request",
    channel: 0,
    response: "voice.mode.set.response",
  },
  "voice.audio.chunk": {
    method: "voice.audio.chunk",
    kind: "event",
    channel: 0,
    response: null,
  },
  "voice.abort.request": {
    method: "voice.abort.request",
    kind: "request",
    channel: 0,
    response: null,
  },
  "voice.audio.played": {
    method: "voice.audio.played",
    kind: "event",
    channel: 0,
    response: null,
  },
  "dictation.stream.start": {
    method: "dictation.stream.start",
    kind: "event",
    channel: 0,
    response: null,
  },
  "dictation.stream.chunk": {
    method: "dictation.stream.chunk",
    kind: "event",
    channel: 0,
    response: null,
  },
  "dictation.stream.finish": {
    method: "dictation.stream.finish",
    kind: "event",
    channel: 0,
    response: null,
  },
  "dictation.stream.cancel": {
    method: "dictation.stream.cancel",
    kind: "event",
    channel: 0,
    response: null,
  },
  "session.events.set_subscription.request": {
    method: "session.events.set_subscription.request",
    kind: "request",
    channel: 0,
    response: "session.events.set_subscription.response",
  },
  "subscription.release.request": {
    method: "subscription.release.request",
    kind: "request",
    channel: 0,
    response: "subscription.release.response",
  },
  "creation.subscribe.request": {
    method: "creation.subscribe.request",
    kind: "request",
    channel: 0,
    response: "creation.subscribe.response",
  },
  "session.heartbeat": {
    method: "session.heartbeat",
    kind: "event",
    channel: 0,
    response: null,
  },
  "connection.ping": {
    method: "connection.ping",
    kind: "request",
    channel: 0,
    response: "connection.pong",
  },
  "push.register": {
    method: "push.register",
    kind: "event",
    channel: 0,
    response: null,
  },
  "push.unregister.request": {
    method: "push.unregister.request",
    kind: "request",
    channel: 0,
    response: "push.unregister.response",
  },
  "browser.host.register.request": {
    method: "browser.host.register.request",
    kind: "request",
    channel: 3,
    response: "browser.host.register.response",
  },
  "browser.automation.execute.response": {
    method: "browser.automation.execute.response",
    kind: "response",
    channel: 3,
    response: null,
  },
  "editor.available.list.request": {
    method: "editor.available.list.request",
    kind: "request",
    channel: 1,
    response: "editor.available.list.response",
  },
  "editor.open.request": {
    method: "editor.open.request",
    kind: "request",
    channel: 1,
    response: "editor.open.response",
  },
};
