[package]
name = "relay"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
futures-util.workspace = true
reqwest.workspace = true
reqwest.features = ["rustls-tls", "stream"]
secrecy.workspace = true
secrecy.features = ["serde"]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tokio-tungstenite.features = ["rustls-tls-webpki-roots"]
tokio-util.workspace = true
url.workspace = true
uuid.workspace = true
uuid.features = ["serde"]

[lints]
workspace = true
