//! Generate missing Git wording outside the serialized filesystem job permit.

use domain::summary::{SummaryKind, SummaryRequest};
use model::ErrorCode;
use serde_json::{Value, json};

use super::State;
use crate::git::service::checkout::{
    CheckoutDiff, CheckoutDiffCompare, CheckoutDiffMode, DiffLineKind,
};

pub(super) async fn fill(state: &State, method: &str, params: &mut Value) -> Result<(), ErrorCode> {
    let (kind, cwd, base_ref) = match method {
        "checkout.commit.request" => {
            let request: crate::git::protocol::checkout::CheckoutCommitRequest =
                serde_json::from_value(params.clone()).map_err(|_| ErrorCode::InvalidMessage)?;
            if !blank(request.message.as_deref()) {
                return Ok(());
            }
            (SummaryKind::CommitMessage, request.cwd, None)
        }
        "checkout.pr.create.request" => {
            let request: crate::forge::protocol::forge::PullRequestCreateRequest =
                serde_json::from_value(params.clone()).map_err(|_| ErrorCode::InvalidMessage)?;
            if !blank(request.title.as_deref()) && !blank(request.body.as_deref()) {
                return Ok(());
            }
            (SummaryKind::PullRequest, request.cwd, request.base_ref)
        }
        _ => return Ok(()),
    };
    let read_cwd = cwd.clone();
    let (root, context) = state
        .run(
            state.checkout.clone(),
            ErrorCode::ProjectIo,
            move |checkout| {
                let status = checkout
                    .status(&read_cwd)
                    .map_err(|_| ErrorCode::ProjectIo)?;
                let diff = checkout
                    .diff(
                        &read_cwd,
                        &CheckoutDiffCompare {
                            mode: if kind == SummaryKind::CommitMessage {
                                CheckoutDiffMode::Uncommitted
                            } else {
                                CheckoutDiffMode::Base
                            },
                            base_ref,
                            ignore_whitespace: false,
                        },
                    )
                    .map_err(|_| ErrorCode::ProjectIo)?;
                Ok((status.repo_root.unwrap_or(read_cwd), source(&diff, kind)))
            },
        )
        .await?;
    let generated = match &state.summary_source {
        Some(generator) => generator
            .generate(SummaryRequest {
                kind,
                cwd: root,
                context,
                selection: None,
            })
            .await
            .ok(),
        None => None,
    };
    apply(params, kind, generated.as_ref());
    Ok(())
}

fn blank(value: Option<&str>) -> bool {
    value.is_none_or(|value| value.trim().is_empty())
}

fn apply(params: &mut Value, kind: SummaryKind, generated: Option<&Value>) {
    let fields: &[(&str, &str)] = match kind {
        SummaryKind::CommitMessage => &[("message", "Update files")],
        SummaryKind::PullRequest => &[
            ("title", "Update changes"),
            ("body", "Automated PR generated by Ait."),
        ],
        SummaryKind::Title | SummaryKind::BranchName => return,
    };
    for (field, fallback) in fields {
        if blank(params.get(field).and_then(Value::as_str)) {
            params[field] = json!(
                generated
                    .and_then(|value| value.get(field))
                    .and_then(Value::as_str)
                    .unwrap_or(fallback)
            );
        }
    }
}

fn source(diff: &CheckoutDiff, kind: SummaryKind) -> String {
    let limit = if kind == SummaryKind::CommitMessage {
        120_000
    } else {
        200_000
    };
    let mut output = String::new();
    append(&mut output, "Changed files:\n", limit);
    for file in &diff.files {
        let status = if file.is_new {
            "A"
        } else if file.is_deleted {
            "D"
        } else if file.old_path.is_some() {
            "R"
        } else {
            "M"
        };
        append(
            &mut output,
            &format!(
                "{status} {} (+{} -{}) {:?}\n",
                file.path, file.additions, file.deletions, file.status
            ),
            limit,
        );
    }
    append(&mut output, "\nPatch:\n", limit);
    for file in &diff.files {
        append(
            &mut output,
            &format!(
                "\n--- {}\n+++ {}\n",
                file.old_path.as_deref().unwrap_or(&file.path),
                file.path
            ),
            limit,
        );
        for hunk in &file.hunks {
            for line in &hunk.lines {
                let prefix = match line.kind {
                    DiffLineKind::Add => "+",
                    DiffLineKind::Remove => "-",
                    DiffLineKind::Context => " ",
                    DiffLineKind::Header => "",
                };
                append(&mut output, prefix, limit);
                append(&mut output, &line.content, limit);
                append(&mut output, "\n", limit);
                if output.len() >= limit {
                    return output;
                }
            }
        }
    }
    output
}

fn append(output: &mut String, text: &str, limit: usize) {
    let mut end = text.len().min(limit.saturating_sub(output.len()));
    while !text.is_char_boundary(end) {
        end -= 1;
    }
    output.push_str(&text[..end]);
}

#[cfg(test)]
mod tests;
